CREATE TABLE USUARIOS
  (
    ID         NUMBER(4) PRIMARY KEY,
    NOMBRE     VARCHAR2(20) NOT NULL,
    APELLIDO   VARCHAR2(20) NOT NULL,
    CORREO     VARCHAR2(30) NOT NULL,
    CONTRASENA VARCHAR2(30) NOT NULL
  );
CREATE TABLE TOPICOS
  (
    ID          NUMBER(4) PRIMARY KEY,
    NOMBRE      VARCHAR2(100) NOT NULL,
    CATEGORIA   VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(4000) NOT NULL,
    ID_USUARIO  NUMBER(4) NOT NULL,
    RUTA_IMAGEN VARCHAR2(100),
    CONSTRAINT FK_USUARIO_TOPICO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
    CONSTRAINT CHECK_CATEGORIA CHECK ("CATEGORIA" IN ('INTRODUCCION A LOS SISTEMAS DISTRIBUIDOS','COMUNICACION EN SISTEMAS DISTRIBUIDOS','SINCRONIZACION EN AMBIENTES DISTRIBUIDOS','REPLICACION','SISTEMAS DE ARCHIVOS DISTRIBUIDOS','SERVICIOS DE NOMBRE','OBJETOS DISTRIBUIDOS','SERVICIOS WEB'))
  );
CREATE TABLE PREGUNTAS
  (
    ID        NUMBER(4) PRIMARY KEY,
    ENUNCIADO VARCHAR2(200) NOT NULL,
    ID_TOPICO NUMBER(4) NOT NULL,
    CONSTRAINT FK_TOPICO_PREGUNTA FOREIGN KEY (ID_TOPICO) REFERENCES TOPICOS(ID)
  );
CREATE TABLE RESPUESTAS
  (
    ID          NUMBER(4) PRIMARY KEY,
    OPCION      VARCHAR2(50) NOT NULL,
    ID_PREGUNTA NUMBER(4) NOT NULL,
    CORRECTA    VARCHAR2(10),
    CONSTRAINT FK_PREGUNTA_RESPUESTA FOREIGN KEY (ID_PREGUNTA) REFERENCES PREGUNTAS(ID),
    CONSTRAINT CHECK_CORRECTA CHECK ("CORRECTA" IN ('SI'))
  );
CREATE TABLE NODOS
  (
    ID             NUMBER(2) PRIMARY KEY,
    IP             VARCHAR2(20) NOT NULL,
    NOMBRE_USUARIO VARCHAR2(20) NOT NULL,
    CONTRASENA     VARCHAR2(20) NOT NULL
  );
CREATE TABLE MENSAJES_AGENTE
  (
    ID                       NUMBER (4) PRIMARY KEY,
    ID_PROCESO               NUMBER(6) NOT NULL,
    CANTIDAD_PROCESOS        NUMBER(4) NOT NULL,
    MEMORIA_DISPONIBLE       NUMBER(5) NOT NULL,
    USO_CPU                  NUMBER(4,2) NOT NULL,
    PUERTOS_DISPONIBLES      VARCHAR2(500) NOT NULL,
    ID_NODO                  NUMBER(4) NOT NULL,
    NOMBRE_APLICACION_ACTUAL VARCHAR2(100),
    ESTADO_APLICACION        VARCHAR2(50),
    CONSTRAINT FK_NODO_MENSAJEAGENTE FOREIGN KEY (ID_NODO) REFERENCES NODOS(ID),
    CONSTRAINT CHECK_ESTADO_APLICACION CHECK ("ESTADO_APLICACION" IN ('ACTIVA','DESACTIVA'))
  );
CREATE TABLE APLICACIONES
  (
    ID                  NUMBER(4) PRIMARY KEY,
    NOMBRE              VARCHAR2(100) NOT NULL,
    FECHA_ACTUALIZACION DATE NOT NULL,
    INSTRUCCIONES       VARCHAR2(4000) NOT NULL,
    ID_TOPICO           NUMBER(4) NOT NULL,
    CONSTRAINT FK_TOPICO_APLICACION FOREIGN KEY (ID_TOPICO) REFERENCES TOPICOS(ID)
  );
CREATE TABLE ESCENARIOS
  (
    ID            NUMBER(4) PRIMARY KEY,
    NOMBRE        VARCHAR2(50) NOT NULL,
    DESCRIPCION   VARCHAR2(4000) NOT NULL,
    ID_APLICACION NUMBER(4) NOT NULL,
    IMAGEN        VARCHAR2(100),
    CONSTRAINT FK_APLICACION_ESCENARIO FOREIGN KEY (ID_APLICACION) REFERENCES APLICACIONES(ID)
  );
CREATE TABLE EJECUTABLES
  (
    ID              NUMBER(4) PRIMARY KEY,
    NOMBRE          VARCHAR2(50) NOT NULL,
    TIPO            VARCHAR2(20) NOT NULL,
    RUTA_EJECUTABLE VARCHAR2(100) NOT NULL,
    ID_APLICACION   NUMBER(4) NOT NULL,
    CONSTRAINT FK_APLICACION_EJECUTABLES FOREIGN KEY (ID_APLICACION) REFERENCES APLICACIONES(ID),
    CONSTRAINT CHECK_TIPO CHECK ("TIPO" IN ('CLIENTE','SERVIDOR'))
  );
CREATE TABLE PARAMETROS
  (
    ID            NUMBER(4) PRIMARY KEY,
    NOMBRE        VARCHAR2(50) NOT NULL,
    VALOR         VARCHAR2(50) NOT NULL,
    ID_EJECUTABLE NUMBER(4) NOT NULL,
    CONSTRAINT FK_EJECUTABLE_PARAMETRO FOREIGN KEY (ID_EJECUTABLE) REFERENCES EJECUTABLES(ID)
  );
CREATE TABLE E_N
  (
    FECHA_DEPLOY  DATE NOT NULL,
    HORA_DEPLOY   DATE NOT NULL,
    ID_PROCESO    NUMBER (6) NOT NULL,
    ID_NODO       NUMBER(4),
    ID_EJECUTABLE NUMBER(4),
    CONSTRAINT PK_P_N PRIMARY KEY (ID_NODO,ID_EJECUTABLE,ID_PROCESO),
    CONSTRAINT FK_NODO_P_N FOREIGN KEY (ID_NODO) REFERENCES NODOS(ID),
    CONSTRAINT FK_EJECUTABLE_P_N FOREIGN KEY (ID_EJECUTABLE) REFERENCES EJECUTABLES(ID)
  );
CREATE TABLE MENSAJE_ENTRE_NODOS
  (
    ID         NUMBER(4) PRIMARY KEY,
    FECHA      DATE NOT NULL,
    HORA       DATE NOT NULL,
    MENSAJE    VARCHAR2(100) NOT NULL,
    IP_DESTINO VARCHAR2(20) NOT NULL,
    ID_NODO    NUMBER(4) NOT NULL,
    ID_EJECUTABLE NUMBER(4) NOT NULL,
    ID_PROCESO    NUMBER(6) NOT NULL,
    CONSTRAINT FK_E_N_MENSAJEENTRENODOS FOREIGN KEY (ID_NODO,ID_EJECUTABLE,ID_PROCESO) REFERENCES E_N(ID_NODO,ID_EJECUTABLE,ID_PROCESO)
  );
CREATE TABLE EVENTOS
  (
    ID         NUMBER(4) PRIMARY KEY,
    NOMBRE     VARCHAR2(20) NOT NULL,
    PATHSCRIPT VARCHAR2(50) NOT NULL
  );
CREATE SEQUENCE S_USUARIOS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_TOPICOS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_PREGUNTAS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_RESPUESTAS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_NODOS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_MENSAJES_AGENTE START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_APLICACIONES START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_ESCENARIOS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_EJECUTABLES START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_PARAMETROS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_MENSAJE_ENTRE_NODOS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
CREATE SEQUENCE S_EVENTOS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;